TYPO3:
  Flow:
    reflection:
      ignoredTags:
        unstable: TRUE

  Neos:
    typoScript:
      autoInclude:
        'Networkteam.Neos.Shariff': TRUE

Networkteam:
  Neos:
    Shariff:
      frontend:
        theme: standard
        orientation: horizontal
        language: en
      options:
        domain: ~
        cache:
          ttl: 3600
        services:
#          - Facebook
#          - GooglePlus
#          - Twitter
#          - LinkedIn
#          - Reddit
#          - StumbleUpon
#          - Flattr
#          - Pinterest
#          - Xing
